export const USERS = [
    { name: 'John', email: 'john@gmail.com' },
    { name: 'Jane', email: 'jane@gmail.com' },
    { name: 'Alice', email: 'alice@gmail.com' },
    { name: 'Bob', email: 'bob@gmail.com' },
    { name: 'Charlie', email: 'charlie@gmail.com' },
    { name: 'David', email: 'david@gmail.com' },
    { name: 'Eve', email: 'eve@gmail.com' },
    { name: 'Frank', email: 'frank@gmail.com' },
    { name: 'Grace', email: 'grace@gmail.com' },
    { name: 'Hank', email: 'hank@gmail.com' },
    { name: 'Ivy', email: 'ivy@gmail.com' },
    { name: 'Jake', email: 'jake@gmail.com' },
    { name: 'Kim', email: 'kim@gmail.com' },
    { name: 'Liam', email: 'liam@gmail.com' },
    { name: 'Mia', email: 'mia@gmail.com' },
    { name: 'Noah', email: 'noah@gmail.com' },
    { name: 'Olivia', email: 'olivia@gmail.com' },
    { name: 'Paul', email: 'paul@gmail.com' },
    { name: 'Quinn', email: 'quinn@gmail.com' },
    { name: 'Ryan', email: 'ryan@gmail.com' },
    { name: 'Sophia', email: 'sophia@gmail.com' },
    { name: 'Tom', email: 'tom@gmail.com' },
    { name: 'Uma', email: 'uma@gmail.com' },
    { name: 'Violet', email: 'violet@gmail.com' },
    { name: 'Will', email: 'will@gmail.com' },
    { name: 'Xander', email: 'xander@gmail.com' },
    { name: 'Yara', email: 'yara@gmail.com' },
    { name: 'Zack', email: 'zack@gmail.com' },
    { name: 'Aiden', email: 'aiden@gmail.com' },
    { name: 'Bella', email: 'bella@gmail.com' }
  ];
  
  